name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Run type checking
      run: pnpm run type-check
    
    - name: Run linting
      run: pnpm run lint
    
    - name: Run tests
      run: pnpm test
    
    - name: Build React app
      run: pnpm run build:react
    
    - name: Build Electron app
      run: pnpm run build:electron

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build application
      run: pnpm run build
    
    - name: Package application
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          pnpm run dist:linux
        elif [ "$RUNNER_OS" == "Windows" ]; then
          pnpm run dist:win
        elif [ "$RUNNER_OS" == "macOS" ]; then
          pnpm run dist:mac
        fi
      shell: bash
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mongo-ui-${{ matrix.os }}
        path: release/